### ISSUE TITLE
Stratum starts, but does not start webserver - errors on Debian 10

### ISSUE THREAD

**Issue by mooleshacat** [Stratehm/stratum-proxy#117]
**I get the following errors on Debian 10**

```
java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.CookieParamValueFactoryProvider
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:389)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:114)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:102)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:153)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2270)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87)
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:58)
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:54)
	at jersey.repackaged.com.google.common.collect.Iterators$8.transform(Iterators.java:860)
	at jersey.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at java.base/java.util.LinkedHashSet.<init>(LinkedHashSet.java:169)
	at jersey.repackaged.com.google.common.collect.Sets.newLinkedHashSet(Sets.java:292)
	at org.glassfish.jersey.internal.inject.Providers.getClasses(Providers.java:378)
	at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:186)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.createValueProviders(ParameterValueHelper.java:109)
	at org.glassfish.jersey.server.model.Invocable.getValueProviders(Invocable.java:322)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkValueProviders(ResourceMethodValidator.java:164)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkMethod(ResourceMethodValidator.java:106)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitJaxrsResourceMethod(ResourceMethodValidator.java:102)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitResourceMethod(ResourceMethodValidator.java:92)
	at org.glassfish.jersey.server.model.ResourceMethod.accept(ResourceMethod.java:854)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:161)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:167)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:167)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:167)
	at org.glassfish.jersey.server.model.ComponentModelValidator.access$000(ComponentModelValidator.java:90)
	at org.glassfish.jersey.server.model.ComponentModelValidator$1.run(ComponentModelValidator.java:151)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validate(ComponentModelValidator.java:146)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:463)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:163)
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:323)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:289)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:286)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:286)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:320)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:285)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:331)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:141)
	at strat.mining.stratum.proxy.Launcher.initHttpServices(Launcher.java:247)
	at strat.mining.stratum.proxy.Launcher.main(Launcher.java:132)
^C2020-05-08 22:06:35,035 INFO     [Thread-1]:strat.mining.stratum.proxy.database.DatabaseManager - Close databases.
2020-05-08 22:06:35,076 INFO     [Thread-1]:strat.mining.stratum.proxy.Launcher$1 - User requested shutdown... Gracefuly kill all connections...
2020-05-08 22:06:35,076 INFO     [Thread-1]:strat.mining.stratum.proxy.manager.ProxyManager - Closing the server socket on /192.168.1.10:3333.
2020-05-08 22:06:35,077 WARN     [Thread-1]:strat.mining.stratum.proxy.manager.ProxyManager - Pool yescrypt.mine.zergpool.com:6233 is DOWN. Moving connections to another one.
2020-05-08 22:06:35,078 INFO     [StratumProxyManagerSeverSocketListener]:strat.mining.stratum.proxy.manager.ProxyManager$1 - Stop to listen incoming connection on /192.168.1.10:3333.
2020-05-08 22:06:35,084 INFO     [Thread-1]:strat.mining.stratum.proxy.pool.Pool - Pool yescrypt.mine.zergpool.com:6233 stopped.
2020-05-08 22:06:35,125 INFO     [Thread-1]:strat.mining.stratum.proxy.Launcher$1 - Shutdown !
kthx@BOX:~/PROXY/stratum-proxy-0.8.1$
```

I have searched everywhere and can't find a solution.

I've installed the compiled binaries because the compilation process failed. The stratum loads and I can connect miners to it but the web server does not load. The same version works on windows, but I want to run it on Linux.

**Thanks**

**Comment by mooleshacat** [comment]
I also have tried to compile the project with no success. I get the following errors on compile:

```
kthx@BOX:/opt/stratum-proxy$ sudo mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< strat.mining.stratum:stratum-proxy >-----------------
[INFO] Building stratum-proxy 0.8.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stratum-proxy ---
[INFO] Deleting /opt/stratum-proxy/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ stratum-proxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 305 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ stratum-proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 107 source files to /opt/stratum-proxy/target/classes
[WARNING] /opt/stratum-proxy/src/main/java/strat/mining/stratum/proxy/cli/BooleanArrayOptionHandler.java: /opt/stratum-proxy/src/main/java/strat/mining/stratum/proxy/cli/BooleanArrayOptionHandler.java uses or overrides a deprecated API.
[WARNING] /opt/stratum-proxy/src/main/java/strat/mining/stratum/proxy/cli/BooleanArrayOptionHandler.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- swagger-maven-plugin:2.3.2:generate (default) @ stratum-proxy ---
[INFO] Reflections took 28 ms to scan 1 urls, producing 12 keys and 25 values 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.850 s
[INFO] Finished at: 2020-05-17T15:48:01-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:2.3.2:generate (default) on project stratum-proxy: Execution default of goal com.github.kongchen:swagger-maven-plugin:2.3.2:generate failed: A required class was missing while executing com.github.kongchen:swagger-maven-plugin:2.3.2:generate: javax/xml/bind/annotation/XmlRootElement
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.kongchen:swagger-maven-plugin:2.3.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/com/github/kongchen/swagger-maven-plugin/2.3.2/swagger-maven-plugin-2.3.2.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[2] = file:/root/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[4] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[5] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar
[ERROR] urls[6] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
[ERROR] urls[7] = file:/root/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
[ERROR] urls[8] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[9] = file:/root/.m2/repository/org/apache/httpcomponents/httpclient/4.2.2/httpclient-4.2.2.jar
[ERROR] urls[10] = file:/root/.m2/repository/org/apache/httpcomponents/httpcore/4.2.2/httpcore-4.2.2.jar
[ERROR] urls[11] = file:/root/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[12] = file:/root/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[ERROR] urls[13] = file:/root/.m2/repository/com/github/spullara/mustache/java/compiler/0.8.12/compiler-0.8.12.jar
[ERROR] urls[14] = file:/root/.m2/repository/com/google/guava/guava/13.0.1/guava-13.0.1.jar
[ERROR] urls[15] = file:/root/.m2/repository/com/wordnik/swagger-jaxrs_2.10/1.3.10/swagger-jaxrs_2.10-1.3.10.jar
[ERROR] urls[16] = file:/root/.m2/repository/org/scala-lang/scala-library/2.10.0/scala-library-2.10.0.jar
[ERROR] urls[17] = file:/root/.m2/repository/com/wordnik/swagger-core_2.10/1.3.10/swagger-core_2.10-1.3.10.jar
[ERROR] urls[18] = file:/root/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[19] = file:/root/.m2/repository/com/fasterxml/jackson/module/jackson-module-scala_2.10/2.4.1/jackson-module-scala_2.10-2.4.1.jar
[ERROR] urls[20] = file:/root/.m2/repository/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar
[ERROR] urls[21] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar
[ERROR] urls[22] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.1.1/jackson-databind-2.4.1.1.jar
[ERROR] urls[23] = file:/root/.m2/repository/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar
[ERROR] urls[24] = file:/root/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[25] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.4.1/jackson-annotations-2.4.1.jar
[ERROR] urls[26] = file:/root/.m2/repository/com/fasterxml/jackson/module/jackson-module-jsonSchema/2.1.0/jackson-module-jsonSchema-2.1.0.jar
[ERROR] urls[27] = file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.0.0/jackson-jaxrs-json-provider-2.0.0.jar
[ERROR] urls[28] = file:/root/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.0.0/jackson-module-jaxb-annotations-2.0.0.jar
[ERROR] urls[29] = file:/root/.m2/repository/com/wordnik/swagger-annotations/1.3.10/swagger-annotations-1.3.10.jar
[ERROR] urls[30] = file:/root/.m2/repository/org/json4s/json4s-ext_2.10/3.2.9/json4s-ext_2.10-3.2.9.jar
[ERROR] urls[31] = file:/root/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar
[ERROR] urls[32] = file:/root/.m2/repository/org/joda/joda-convert/1.6/joda-convert-1.6.jar
[ERROR] urls[33] = file:/root/.m2/repository/org/json4s/json4s-native_2.10/3.2.9/json4s-native_2.10-3.2.9.jar
[ERROR] urls[34] = file:/root/.m2/repository/org/json4s/json4s-core_2.10/3.2.9/json4s-core_2.10-3.2.9.jar
[ERROR] urls[35] = file:/root/.m2/repository/org/json4s/json4s-ast_2.10/3.2.9/json4s-ast_2.10-3.2.9.jar
[ERROR] urls[36] = file:/root/.m2/repository/org/scala-lang/scalap/2.10.0/scalap-2.10.0.jar
[ERROR] urls[37] = file:/root/.m2/repository/org/scala-lang/scala-compiler/2.10.0/scala-compiler-2.10.0.jar
[ERROR] urls[38] = file:/root/.m2/repository/org/json4s/json4s-jackson_2.10/3.2.9/json4s-jackson_2.10-3.2.9.jar
[ERROR] urls[39] = file:/root/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
[ERROR] urls[40] = file:/root/.m2/repository/org/reflections/reflections/0.9.9/reflections-0.9.9.jar
[ERROR] urls[41] = file:/root/.m2/repository/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar
[ERROR] urls[42] = file:/root/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar
[ERROR] urls[43] = file:/root/.m2/repository/commons-io/commons-io/2.0.1/commons-io-2.0.1.jar
[ERROR] urls[44] = file:/root/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar
[ERROR] urls[45] = file:/root/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
[ERROR] urls[46] = file:/root/.m2/repository/com/wordnik/swagger-jersey-jaxrs_2.10/1.3.10/swagger-jersey-jaxrs_2.10-1.3.10.jar
[ERROR] urls[47] = file:/root/.m2/repository/com/sun/jersey/contribs/jersey-multipart/1.13/jersey-multipart-1.13.jar
[ERROR] urls[48] = file:/root/.m2/repository/org/jvnet/mimepull/1.6/mimepull-1.6.jar
[ERROR] urls[49] = file:/root/.m2/repository/com/sun/jersey/jersey-servlet/1.13/jersey-servlet-1.13.jar
[ERROR] urls[50] = file:/root/.m2/repository/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.jar
[ERROR] urls[51] = file:/root/.m2/repository/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.jar
[ERROR] urls[52] = file:/root/.m2/repository/com/sun/jersey/jersey-server/1.13/jersey-server-1.13.jar
[ERROR] urls[53] = file:/root/.m2/repository/asm/asm/3.1/asm-3.1.jar
[ERROR] urls[54] = file:/opt/stratum-proxy/target/classes/
[ERROR] urls[55] = file:/root/.m2/repository/org/glassfish/jersey/containers/jersey-container-grizzly2-http/2.14/jersey-container-grizzly2-http-2.14.jar
[ERROR] urls[56] = file:/root/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b06/javax.inject-2.4.0-b06.jar
[ERROR] urls[57] = file:/root/.m2/repository/org/glassfish/grizzly/grizzly-http-server/2.3.16/grizzly-http-server-2.3.16.jar
[ERROR] urls[58] = file:/root/.m2/repository/org/glassfish/grizzly/grizzly-http/2.3.16/grizzly-http-2.3.16.jar
[ERROR] urls[59] = file:/root/.m2/repository/org/glassfish/grizzly/grizzly-framework/2.3.16/grizzly-framework-2.3.16.jar
[ERROR] urls[60] = file:/root/.m2/repository/org/glassfish/jersey/core/jersey-common/2.14/jersey-common-2.14.jar
[ERROR] urls[61] = file:/root/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[62] = file:/root/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.14/jersey-guava-2.14.jar
[ERROR] urls[63] = file:/root/.m2/repository/org/glassfish/hk2/hk2-api/2.4.0-b06/hk2-api-2.4.0-b06.jar
[ERROR] urls[64] = file:/root/.m2/repository/org/glassfish/hk2/hk2-utils/2.4.0-b06/hk2-utils-2.4.0-b06.jar
[ERROR] urls[65] = file:/root/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b06/aopalliance-repackaged-2.4.0-b06.jar
[ERROR] urls[66] = file:/root/.m2/repository/org/glassfish/hk2/hk2-locator/2.4.0-b06/hk2-locator-2.4.0-b06.jar
[ERROR] urls[67] = file:/root/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
[ERROR] urls[68] = file:/root/.m2/repository/org/glassfish/jersey/core/jersey-server/2.14/jersey-server-2.14.jar
[ERROR] urls[69] = file:/root/.m2/repository/org/glassfish/jersey/core/jersey-client/2.14/jersey-client-2.14.jar
[ERROR] urls[70] = file:/root/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
[ERROR] urls[71] = file:/root/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/2.14/jersey-media-json-jackson-2.14.jar
[ERROR] urls[72] = file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.3.2/jackson-jaxrs-base-2.3.2.jar
[ERROR] urls[73] = file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.3.2/jackson-jaxrs-json-provider-2.3.2.jar
[ERROR] urls[74] = file:/root/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.3.2/jackson-module-jaxb-annotations-2.3.2.jar
[ERROR] urls[75] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.0/jackson-databind-2.5.0.jar
[ERROR] urls[76] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.0/jackson-core-2.5.0.jar
[ERROR] urls[77] = file:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar
[ERROR] urls[78] = file:/root/.m2/repository/args4j/args4j/2.0.29/args4j-2.0.29.jar
[ERROR] urls[79] = file:/root/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar
[ERROR] urls[80] = file:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar
[ERROR] urls[81] = file:/root/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[82] = file:/root/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.jar
[ERROR] urls[83] = file:/root/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[84] = file:/root/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[85] = file:/root/.m2/repository/com/db4o/db4o-all-java5/8.0.249.16098/db4o-all-java5-8.0.249.16098.jar
[ERROR] urls[86] = file:/root/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.51/bcpkix-jdk15on-1.51.jar
[ERROR] urls[87] = file:/root/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar
[ERROR] urls[88] = file:/root/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar
[ERROR] urls[89] = file:/root/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar
[ERROR] urls[90] = file:/root/.m2/repository/com/wordnik/swagger-annotations/1.3.12/swagger-annotations-1.3.12.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.xml.bind.annotation.XmlRootElement
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
kthx@BOX:/opt/stratum-proxy$ 
```

Please advise on what to do... Thanks
