### ISSUE TITLE
Build Attempt

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#36]
When attempting to build the application I receive the error

`

Tracing dependencies for: main
Error: Error: Loader plugin did not call the load callback in the build:
rv:
  rv!templates/mainContainer_unnormalized2: Error: Load timeout for modules: rv!templates/mainContainer_unnormalized2
http://requirejs.org/docs/errors.html#timeout
Module loading did not complete for: main, stratum-proxy-client
    at Function.build.checkForErrors (/opt/stratum-proxy/lib/javascript/r/r.js:27435:19)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:11.681s
[INFO] Finished at: Mon Mar 30 12:00:23 UTC 2015
[INFO] Final Memory: 18M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.bringking:requirejs-maven-plugin:2.0.4:optimize (default) on project stratum-proxy: r.js exited with an error. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

Any ideas?

**Comment by computeronix** [comment]
with debug run

`

Optimizing (standard) CSS file: /opt/stratum-proxy/target/webapp-optimizer/css/stratumProxy.css

Tracing dependencies for: main
Error: Error: Loader plugin did not call the load callback in the build:
rv:
  rv!templates/mainContainer_unnormalized2: Error: Load timeout for modules: rv!templates/mainContainer_unnormalized2
http://requirejs.org/docs/errors.html#timeout
Module loading did not complete for: main, stratum-proxy-client
    at Function.build.checkForErrors (/opt/stratum-proxy/lib/javascript/r/r.js:27435:19)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:26.689s
[INFO] Finished at: Mon Mar 30 19:22:32 UTC 2015
[INFO] Final Memory: 17M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.bringking:requirejs-maven-plugin:2.0.4:optimize (default) on project stratum-proxy: r.js exited with an error. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.bringking:requirejs-maven-plugin:2.0.4:optimize (default) on project stratum-proxy: r.js exited with an error.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: r.js exited with an error.
        at com.github.bringking.maven.requirejs.OptimizeMojo.execute(OptimizeMojo.java:150)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by Stratehm** [comment]
Do you have NodeJS installed on your system ? 

When the optimizer run in the Rhino engine (the default Javascript engine of Java), it is so slow that it may run into timeout.

You should install NodeJS and make sure it is in your PATH;

**Comment by computeronix** [comment]
nodejs is installed and I can call node and npm from the command line

**Comment by computeronix** [comment]
when do you think the next release will be available?  I don't really need to build a version as the latest release with the API change will work :)

**Comment by Stratehm** [comment]
0.7.0 version released: https://github.com/Stratehm/stratum-proxy/releases
