### ISSUE TITLE
Parsing error on worker connection

### ISSUE THREAD

**Issue by vanch** [Stratehm/stratum-proxy#55]
Hi there it seems like you made a mistake when commit https://github.com/Stratehm/stratum-proxy/commit/fee90448fbb120bfeec328697542628124bd1f4e cause now it causes error:

```
2015-08-19 10:16:48,482 ERROR [10.12.13.73-Thread]: [WorkerConnection]    Parsing error on worker connection 10.12.13.73. Failed to parse line {"
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
     at java.util.ArrayList.get(ArrayList.java:429)
     at strat.mining.stratum.proxy.json.MiningGetTransactionsRequest.setParams(MiningGetTransactionsRequest.java:65)
     at strat.mining.stratum.proxy.json.JsonRpcRequest.<init>(JsonRpcRequest.java:64)
     at strat.mining.stratum.proxy.json.MiningGetTransactionsRequest.<init>(MiningGetTransactionsRequest.java:40)
     at strat.mining.stratum.proxy.network.StratumConnection.onRequestReceived(StratumConnection.java:369)
     at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:234)
     at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:59)
     at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)
```

Seems like just wrong array addressing and at https://github.com/Stratehm/stratum-proxy/blob/fee90448fbb120bfeec328697542628124bd1f4e/src/main/java/strat/mining/stratum/proxy/json/MiningGetTransactionsRequest.java#L65 instead of
```jobId = (String) params.get(1);```
there should be (maybe)
```jobId = (String) params.get(0);```
uh?

**Comment by Stratehm** [comment]
Fixed. Thank you for your feedback.
