### ISSUE TITLE
ERROR [main]: [Launcher]    Failed to start the proxy and Failed to start Grizzly HTTP server: Cannot assign requested address: bind.

### ISSUE THREAD

**Issue by jeong760** [Stratehm/stratum-proxy#70]
Dears,

I was installed a straum-proxy for eloipool and connect a pool is ok and working fine except the follwoing error messages. in the result I cannot connect and see a wbe statices pages. 

Could you guide me a tips or solution?

2016-04-26 11:39:37,094 INFO  [main]: [Launcher]    Using INFO LogLevel.
2016-04-26 11:39:37,106 INFO  [main]: [Launcher]    API log level set to INFO.
2016-04-26 11:39:37,146 INFO  [main]: [Launcher]    Using database directory: C:\stratum-proxy\database.
2016-04-26 11:39:37,167 INFO  [main]: [DatabaseManager]    Starting DatabaseManager...
2016-04-26 11:39:37,801 INFO  [main]: [DatabaseManager]    DatabaseManager started.
2016-04-26 11:39:37,806 INFO  [main]: [Launcher]    Using pools: [Pool [name=Eloipoolsrv, host=192.168.1.10:3334, username=jeong760, password=usas3amara3ekE6uBu6, readySince=null, isReady=false, isEnabled=true, isStable=false, priority=0, weight=1]].
2016-04-26 11:39:37,837 INFO  [main]: [ProxyManager]    ServerSocket opened on /192.168.1.2:3333.
2016-04-26 11:39:37,853 INFO  [pool-1-thread-1]: [Pool]    Suggest the difficulty 5.0 to the pool Eloipoolsrv.
2016-04-26 11:39:37,937 INFO  [StratumProxyManagerSeverSocketListener]: [ProxyManager]    New connection on /192.168.1.2:3333 from /192.168.1.3:53187.
2016-04-26 11:39:37,987 WARN  [Pool-Eloipoolsrv-Thread]: [StratumConnection]    Unknown response type on connection Pool-Eloipoolsrv. methodName: mining.suggest_difficulty, result: null
2016-04-26 11:39:37,990 ERROR [192.168.1.3-Thread]: [WorkerConnection]    No pool available for the connection 192.168.1.3. Sending error and close the connection.
2016-04-26 11:39:38,000 INFO  [Pool-Eloipoolsrv-Thread]: [ProxyManager]    Set difficulty 255.99609375 on pool Eloipoolsrv.
2016-04-26 11:39:38,012 INFO  [192.168.1.3-Thread]: [ProxyManager]    Worker connection 192.168.1.3 closed. 0 connections active on pool None. Cause: Connection closed.
2016-04-26 11:39:38,013 INFO  [StratumProxyManagerSeverSocketListener]: [ProxyManager]    New connection on /192.168.1.2:3333 from /192.168.1.3:53188.
2016-04-26 11:39:38,039 ERROR [192.168.1.3-Thread]: [WorkerConnection]    No pool available for the connection 192.168.1.3. Sending error and close the connection.
2016-04-26 11:39:38,050 INFO  [Pool-Eloipoolsrv-Thread]: [Pool]    Pool Eloipoolsrv started
2016-04-26 11:39:38,056 INFO  [192.168.1.3-Thread]: [ProxyManager]    Worker connection 192.168.1.3 closed. 0 connections active on pool None. Cause: Connection closed.
2016-04-26 11:39:38,058 WARN  [Pool-Eloipoolsrv-Thread]: [ProxyManager]    Pool Eloipoolsrv is STABLE.
2016-04-26 11:39:38,070 WARN  [Pool-Eloipoolsrv-Thread]: [ProxyManager]    Pool Eloipoolsrv is UP.
2016-04-26 11:39:38,445 ERROR [main]: [Launcher]    Failed to start the proxy.
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address: bind
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:302)
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:90)
    at strat.mining.stratum.proxy.Launcher.initGetwork(Launcher.java:345)
    at strat.mining.stratum.proxy.Launcher.main(Launcher.java:129)
Caused by: java.net.BindException: Cannot assign requested address: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:132)
    at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:236)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:216)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:207)
    at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:680)
    at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278)
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299)
    ... 3 more

Regards,
John Ahn

**Comment by Stratehm** [comment]
Try to change the Getwork listening port. The default one may be already used by another program (like a coin wallet for exemple).
"getworkListenPort" : 8332, // Change me

 If do not need Getwork, you can disable it:
  "disableGetwork": true,
