### ISSUE TITLE
JSON-RPC parsing error with line

### ISSUE THREAD

**Issue by jeong760** [Stratehm/stratum-proxy#71]
Dears,

I've got following message also

2016-04-26 14:54:33,899 ERROR    [Pool-Eloipoolsrv-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-Eloipoolsrv. JSON-RPC parsing error with line: {"error": [-3, "Method 'mining.extranonce.subscribe' not found", null], "id": 4, "result": null}.
java.lang.NullPointerException
        at strat.mining.stratum.proxy.pool.Pool.processSubscribeExtranonceResponse(Pool.java:492)
        at strat.mining.stratum.proxy.pool.PoolConnection.onExtranonceSubscribeResponse(PoolConnection.java:136)
        at strat.mining.stratum.proxy.network.StratumConnection.onResponseReceived(StratumConnection.java:321)
        at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:239)
        at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:58)
        at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:162)

Regards,
John Ahn

**Comment by Stratehm** [comment]
The pool seems to not support the extranonce extension. Try to turn off this feature in your pool configuration:
"enableExtranonceSubscribe" : false,
