### ISSUE TITLE
strat.mining.stratum.proxy.pool.PoolConnection - Pool-xxxxx. JSON -RPC parsing error with line

### ISSUE THREAD

**Issue by hextrip** [Stratehm/stratum-proxy#76]
stratum-proxy.conf:
```
{
  "isScrypt" : false,
  "disableStratum" : false,
  "pools" :
  [
  {
    "name" : "Nicehash Equihash EU",
    "host" : "stratum.nicehash.com:3357",
    "user" : "1Hidehidehidehidehide",
    "password" : "d=0.02",
    "enableExtranonceSubscribe" : true
  },
  {
    "name" : "Westhash Equihash USA",
    "host" : "equihash.usa.nicehash.com:3357",
    "user" : "1Hidehidehidehidehide",
    "password" : "d=0.02",
    "enableExtranonceSubscribe" : true
  }
  ]
}
```

and I'm running `java -jar stratum-proxy.jar -f t.conf`
```
Log directory not set. Use the tmp OS directory.
Use log directory /tmp
2016-11-25 20:34:29,561 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - Using INFO LogLevel.
2016-11-25 20:34:29,566 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - API log level not set. API logging disabled.
2016-11-25 20:34:29,631 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - Database directory not specified. Using defau$
t one: /data/proxy/stratum-proxy-0.8.1-SNAPSHOT/database.
2016-11-25 20:34:29,645 INFO     [main]:strat.mining.stratum.proxy.database.DatabaseManager - Starting DatabaseManager...
2016-11-25 20:34:30,777 INFO     [main]:strat.mining.stratum.proxy.database.DatabaseManager - DatabaseManager started.
2016-11-25 20:34:30,781 INFO     [main]:strat.mining.stratum.proxy.Launcher - Using pools: [Pool [name=Nicehash Equihash EU, host=stratum.nicehash.co$
:3357, username=1NuzWWdpsarMW7CRF7wybTyeAWyfg9ixnh, password=d=0.02, readySince=null, isReady=false, isEnabled=true, isStable=false, priority=0, weig$
t=1], Pool [name=Westhash Equihash USA, host=equihash.usa.nicehash.com:3357, username=1NuzWWdpsarMW7CRF7wybTyeAWyfg9ixnh, password=d=0.02, readySince$
null, isReady=false, isEnabled=true, isStable=false, priority=1, weight=1]].
2016-11-25 20:34:30,805 INFO     [main]:strat.mining.stratum.proxy.manager.ProxyManager - ServerSocket opened on /0.0.0.0:3333.
2016-11-25 20:34:31,403 ERROR    [Pool-Westhash Equihash USA-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-Westhash Equihash USA. JSON
-RPC parsing error with line: {"id":0,"error":null,"result":[null,"8072273745"]}.
java.lang.NullPointerException
        at strat.mining.stratum.proxy.pool.Pool.processSubscribeResponse(Pool.java:452)
        at strat.mining.stratum.proxy.pool.PoolConnection.onSubscribeResponse(PoolConnection.java:137)
        at strat.mining.stratum.proxy.network.StratumConnection.onResponseReceived(StratumConnection.java:310)
        at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:240)
        at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:59)
        at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)
2016-11-25 20:34:31,806 ERROR    [Pool-Nicehash Equihash EU-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-Nicehash Equihash EU. JSON-R
PC parsing error with line: {"id":1,"error":null,"result":[null,"ae384748f8873248739d31180cc5a70abd"]}.
java.lang.NullPointerException
        at strat.mining.stratum.proxy.pool.Pool.processSubscribeResponse(Pool.java:452)
        at strat.mining.stratum.proxy.pool.PoolConnection.onSubscribeResponse(PoolConnection.java:137)
        at strat.mining.stratum.proxy.network.StratumConnection.onResponseReceived(StratumConnection.java:310)
        at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:240)
        at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:59)
        at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)
Nov 25, 2016 8:34:31 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8332]
Nov 25, 2016 8:34:31 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
2016-11-25 20:34:35,769 INFO     [main]:org.reflections.Reflections - Reflections took 925 ms to scan 1 urls, producing 15 keys and 144 values
Nov 25, 2016 8:34:35 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8888]
Nov 25, 2016 8:34:35 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer-1] Started.
2016-11-25 20:35:01,186 ERROR    [Pool-Westhash Equihash USA-Thread]:strat.mining.stratum.proxy.pool.Pool - Disconnection of pool Pool [name=Westhash
Equihash USA, host=equihash.usa.nicehash.com:3357, username=1NuzWWdpsarMW7CRF7wybTyeAWyfg9ixnh, password=d=0.02, readySince=null, isReady=false, isEna
bled=true, isStable=false, priority=1, weight=1].
java.io.EOFException: Connection closed.
        at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:167)
2016-11-25 20:35:01,187 WARN     [Pool-Westhash Equihash USA-Thread]:strat.mining.stratum.proxy.manager.ProxyManager - Pool Westhash Equihash USA is D
OWN. Moving connections to another one.
```

**Comment by BaalMcKloud** [comment]
Equihash is not supported
