### ISSUE TITLE
NiceHash - Solo minig - Vallet

### ISSUE THREAD

**Issue by RommieATIKA** [Stratehm/stratum-proxy#91]
When connecting to NiсeHash stratum+tcp://stratum.solo.nicehash.com:3336/#xnsub for Dash, it is not possible to enter the address of the purse, gives an error, the wallet does not fit, what's wrong?
And with the purse of NikeHash everything is fine, but this is a purse for BITKOIN.

**Comment by BaalMcKloud** [comment]
Try to mine directly to nicehash with your dash adress without the proxy and check if it works.

**Comment by RommieATIKA** [comment]
Yes, it works, when connected, it gives out:

java -jar stratum-proxy.jar -f nicehash-X11-SOLO-NEW.conf
Log directory not set. Use the tmp OS directory.

2017-10-06 13:13:12,155 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - Using INFO LogLevel.
2017-10-06 13:13:12,160 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - API log level not set. API logging disabled.
2017-10-06 13:13:12,194 INFO     [main]:strat.mining.stratum.proxy.configuration.ConfigurationManager - Database directory not specified. Using default one: __________________________\database.
2017-10-06 13:13:12,205 INFO     [main]:strat.mining.stratum.proxy.database.DatabaseManager - Starting DatabaseManager...
2017-10-06 13:13:12,614 INFO     [main]:strat.mining.stratum.proxy.database.DatabaseManager - DatabaseManager started.
2017-10-06 13:13:12,615 INFO     [main]:strat.mining.stratum.proxy.Launcher - Using pools: [Pool [name=Nicehash Solo X11-DASH SOLO VALET, host=stratum.solo.nicehash.com/#
xnsub:3336, username=XyKwA2xWjjx4zLHM8hnGdRpJEbi6KG7zjk.POOL, password=XXX, readySince=null, isReady=false, isEnabled=true, isStable=false, priority=0, weight=1]].
2017-10-06 13:13:12,857 INFO     [main]:strat.mining.stratum.proxy.manager.ProxyManager - ServerSocket opened on /0.0.0.0:9333.
юъЄ 06, 2017 1:13:13 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8336]
юъЄ 06, 2017 1:13:13 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
2017-10-06 13:13:13,437 ERROR    [Pool-Nicehash Solo X11-DASH SOLO VALET-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-Nicehash Solo X11-DASH SOLO VALET.
JSON-RPC parsing error with line: {"id":2,"result":false,"error":"Not a valid address"}.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at strat.mining.stratum.proxy.json.JsonRpcResponse.getJsonError(JsonRpcResponse.java:94)
        at strat.mining.stratum.proxy.pool.Pool.processAuthorizeResponse(Pool.java:534)
        at strat.mining.stratum.proxy.pool.PoolConnection.onAuthorizeResponse(PoolConnection.java:132)
        at strat.mining.stratum.proxy.network.StratumConnection.onResponseReceived(StratumConnection.java:304)
        at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:240)
        at strat.mining.stratum.proxy.network.StratumConnection.access$2(StratumConnection.java:221)
        at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)
2017-10-06 13:13:14,686 INFO     [main]:org.reflections.Reflections - Reflections took 207 ms to scan 1 urls, producing 15 keys and 144 values
юъЄ 06, 2017 1:13:14 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:3388]
юъЄ 06, 2017 1:13:14 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer-1] Started.

**Comment by phush0** [comment]
host=stratum.solo.nicehash.com/#xnsub:3336
have to be 
host=stratum.solo.nicehash.com:3336#xnsub
and better be
host=stratum.solo.nicehash.com:3336
server know that proxy have xnsub
