### ISSUE TITLE
Cannot connect to suprnova pool

### ISSUE THREAD

**Issue by beardJohn** [Stratehm/stratum-proxy#92]
Cannot connect to LBRY.suprnova.cc. It throws exception.

Config File:
{
  "isScrypt" : false,
  "pools" :
  [
  {
    "name" : "LBRY pool suprnova",
    "host" : "lbry.suprnova.cc:6256",
    "user" : "bjinvest",
    "password" : "x",
    "appendWorkerNames" : false,
    "workerNameSeparator" : ".",
    "enableExtranonceSubscribe" : true
  }
  ]
}

Exception:
2017-11-07 14:25:13,744 ERROR    [Pool-LBRY pool suprnova-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-LBRY pool suprnova. JSON-RPC parsing error with line: {"id":null,"method":"mining.notify","params":["210","59685de6f5695e1ccd25fc4323572ca26b6c6957ca39db411d5fc9bdfc245daa","fafef41006d87c354690e475e06df33240e26d5951b55e8ebca8e8289c9f7f66","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff20038e19040449c2015a08","0d2f6e6f64655374726174756d2f0000000001fce1c7f6080000001976a914cfab870d6deea54ca94a41912a75484649e52f2088ac00000000",["e935de839f8ae1f8610cdfb39e5156eb4777073c70590d2338684ef8630464d7","84d1781c891a263e31379b7510f61befc336507e757149ebb5335871d012efac"],"20000000","1a496db0","5a01c249",false]}.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at strat.mining.stratum.proxy.json.MiningNotifyNotification.setParams(MiningNotifyNotification.java:157)
	at strat.mining.stratum.proxy.json.JsonRpcNotification.<init>(JsonRpcNotification.java:46)
	at strat.mining.stratum.proxy.json.MiningNotifyNotification.<init>(MiningNotifyNotification.java:56)
	at strat.mining.stratum.proxy.network.StratumConnection.onNotificationReceived(StratumConnection.java:268)
	at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:247)
	at strat.mining.stratum.proxy.network.StratumConnection.access$2(StratumConnection.java:221)
	at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)

**Comment by dwayneem** [comment]
I have the exact same exception. Tried suprnova, luckpool, bitcoinzguiding, miningspeed, and equipool before giving up and coming here for help.  Did you ever find a solution? I have not had much luck googling for an answer.

**Comment by nukepower** [comment]
unless this proxy has been updated it won't work on sites like suprnova because it doesn't support those type coins when it was written it only supports Sha256 type coins aka bitcoins and Script type coins . it even tells you that in the errors .  i guess some other gave up stressing that for a while some were telling others it won't work on those type pools ..
