### ISSUE TITLE
NiceHash : parse error

### ISSUE THREAD

**Issue by nico579** [Stratehm/stratum-proxy#97]
Hello,

I cant use cpuminer with the proxy : 
on my local computer :
./cpuminer -a x11 -o stratum+tcp://x11.eu.nicehash.com:3336 -u 3JiLakn3G9mHWjnC5Mr65MnXrXcTX4Hue9 -x http://nicmar.fr:3333

my configuration file on the server :
{"pools" : [{"host" : "x11.eu.nicehash.com:3336","user" : "3JiLakn3G9mHWjnC5Mr65MnXrXcTX4Hue9"}]}

the error logs :

 New connection on /0.0.0.0:3333 from /176.137.53.155:38496.
2018-01-07 08:44:47,125 ERROR    [176.137.53.155-Thread]:strat.mining.stratum.proxy.worker.StratumWorkerConnection - Parsing error on worker connection 176.137.53.155. Failed to parse line CONNECT x11.eu.nicehash.com:3336 HTTP/1.1.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'CONNECT': was expecting ('true', 'false' or 'null')
 at [Source: CONNECT x11.eu.nicehash.com:3336 HTTP/1.1; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1459)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
	at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:225)
	at strat.mining.stratum.proxy.network.StratumConnection.access$2(StratumConnection.java:221)
	at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)

Where is the problem ?

Thanks

Nico

**Comment by nukepower** [comment]
only works with sha256 and scrypt algorithm won't work with X11 miner has to be update for other algorithm if i knew how to i would sadly i don't.

**Comment by nico579** [comment]
Thanks nukepower, but i can use with this syntax (without -x) :
  cpuminer -a neoscrypt -o http://nicmar.fr:8332

**Comment by nico579** [comment]
cpuminer -a neoscrypt -o http://nicmar.fr:8332
